# Generated by Django 6.1.1 on 2026-10-04 13:58

import catalog.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, help_text='JPG, PNG o WebP, máximo 2 MB.', upload_to='products/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), catalog.validators.validate_image_size], verbose_name='imagen'),
        ),
    ]
