# Generated by Django 6.1.1 on 2026-10-04 14:57

import catalog.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, help_text='JPG, PNG o WebP, máximo 2 MB.', upload_to='products/', validators=[catalog.validators.validate_image_upload], verbose_name='imagen'),
        ),
    ]
